CREATE SCHEMA IF NOT EXISTS course_lab;

DROP TABLE IF EXISTS course_lab.order_audit;
DROP TABLE IF EXISTS course_lab.order_queue;

CREATE TABLE course_lab.order_queue (
    order_id integer PRIMARY KEY,
    customer_id integer NOT NULL,
    status text NOT NULL CHECK (status IN ('draft', 'pending', 'processing', 'cancelled', 'done')),
    total_amount numeric(12, 2) NOT NULL CHECK (total_amount >= 0),
    idempotency_key text NOT NULL UNIQUE,
    created_at timestamp NOT NULL,
    processed_at timestamp,
    cancelled_reason text
);

CREATE TABLE course_lab.order_audit (
    audit_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id integer NOT NULL REFERENCES course_lab.order_queue(order_id),
    action text NOT NULL,
    created_at timestamp NOT NULL DEFAULT current_timestamp,
    UNIQUE (order_id, action)
);

INSERT INTO course_lab.order_queue
    (order_id, customer_id, status, total_amount, idempotency_key, created_at)
VALUES
    (101, 1, 'pending', 125000.00, 'idem-101', timestamp '2026-02-01 10:00:00'),
    (102, 1, 'pending',  42000.00, 'idem-102', timestamp '2026-02-01 10:05:00'),
    (103, 2, 'pending', 215000.00, 'idem-103', timestamp '2026-02-01 10:10:00'),
    (104, 3, 'draft',    1500.00, 'idem-104', timestamp '2025-12-01 09:00:00'),
    (105, 3, 'draft',    9900.00, 'idem-105', timestamp '2026-02-01 11:00:00'),
    (106, 4, 'done',    74000.00, 'idem-106', timestamp '2026-01-15 12:00:00'),
    (107, 5, 'pending', 180000.00, 'idem-107', timestamp '2026-02-01 12:30:00');
