CREATE SCHEMA IF NOT EXISTS app;

DROP TABLE IF EXISTS app.documents;
DROP TABLE IF EXISTS app.orders;
DROP TABLE IF EXISTS app.events;

CREATE TABLE app.events (
    event_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id integer NOT NULL,
    event_type text NOT NULL,
    payload jsonb NOT NULL,
    created_at timestamptz NOT NULL
);

CREATE TABLE app.orders (
    order_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id integer NOT NULL,
    status text NOT NULL,
    total_amount numeric(12, 2) NOT NULL CHECK (total_amount >= 0),
    idempotency_key text NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    UNIQUE (tenant_id, idempotency_key)
);

CREATE TABLE app.documents (
    document_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id integer NOT NULL,
    title text NOT NULL,
    body text NOT NULL,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL
);

INSERT INTO app.events (tenant_id, event_type, payload, created_at)
SELECT
    1 + (g % 3),
    CASE WHEN g % 5 = 0 THEN 'payment_failed' ELSE 'order_updated' END,
    jsonb_build_object('order_id', g, 'source', CASE WHEN g % 2 = 0 THEN 'api' ELSE 'worker' END),
    timestamp '2026-01-01 00:00:00+00' + (g || ' minutes')::interval
FROM generate_series(1, 5000) AS g;

INSERT INTO app.orders (tenant_id, status, total_amount, idempotency_key, created_at, updated_at)
SELECT
    1 + (g % 3),
    CASE WHEN g % 7 = 0 THEN 'cancelled' WHEN g % 5 = 0 THEN 'processing' ELSE 'created' END,
    (100 + (g % 1000))::numeric(12, 2),
    'order-' || g,
    timestamp '2026-01-01 00:00:00+00' + (g || ' minutes')::interval,
    timestamp '2026-01-01 00:00:00+00' + (g || ' minutes')::interval
FROM generate_series(1, 2000) AS g;

INSERT INTO app.documents (tenant_id, title, body, metadata, created_at)
SELECT
    1 + (g % 3),
    'Document ' || g,
    repeat('database course document ', 10) || g,
    jsonb_build_object('category', CASE WHEN g % 4 = 0 THEN 'billing' ELSE 'support' END, 'priority', g % 5),
    timestamp '2026-01-01 00:00:00+00' + (g || ' minutes')::interval
FROM generate_series(1, 1000) AS g;
